name: build and deploy 
inputs: 
  variables: 
    description: All variables scoped to the environment
    required: true
runs:
  using: "composite"
  steps: 
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - uses: ./.github/actions/deploy
        with: 
          url: ${{ variables.URL }}
