name: dev
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
  build:
    runs-on: ubuntu-latest
    environment: dev  
    needs: [checkout]
    steps:      
      - uses: ./.github/actions/build.yml

  deploy: 
    runs-on: ubuntu-latest
    needs: [build]
    environment: dev
    steps:
      - uses: ./.github/actions/deploy.yml
        

        
  
