name: dev
on:
  push:
    branches: [ "main" ]
    tags: 
      - '**'
    
  workflow_dispatch:
  


jobs:
  build-and-deploy:
    uses: ./.github/workflows/ci-cd.yml
    with:
      environment: dev
            
  #     - uses: actions/checkout@v3
  #   environment: dev  
  # build:
  #   runs-on: ubuntu-latest
  #   environment: dev  
  #   steps:  
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/build        

  # deploy: 
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   environment: dev
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/deploy
  #       with: 
  #         url: ${{ vars.URL }}
        

        
  
