name: dev
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    environment: dev    
    steps:      
      - uses: ./.github/actions/build.yml

  deploy: 
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - uses: ./.github/actions/deploy.yml
        

        
  
