name: dev
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest
    environment: dev  
    steps:  
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build        

  deploy: 
    runs-on: ubuntu-latest
    needs: [build]
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with: 
          url: ${{ vars.URL }}
        

        
  
