name: ephemeral
on: 
  pull_request:
      types: [opened, reopened]
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    environment: ephemeral
    steps:      
      - uses: ./.github/actions/build.yml

  deploy: 
    runs-on: ubuntu-latest
    needs: [build]
    environment: ephemeral
    steps:
      - uses: ./.github/actions/deploy.yml
        

        
