name: ephemeral
on: 
  pull_request:
      types: [opened, reopened]
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    environment: ephemeral
    steps:      
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build 

  deploy: 
    runs-on: ubuntu-latest
    needs: [build]
    environment: ephemeral
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with: 
          url: ${{ vars.URL }}        
