name: test
on: 
  push:
    branches: [ "main" ]
jobs:
  test-bot:
    name: test bot
    runs-on: ubuntu-latest    
    permissions:
      contents: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.CATIONS_APP_ID }}
          private-key: ${{ secrets.CATIONS_PRIVATE_KEY }}
